name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.0]

    steps:
      # ---------- 1. Checkout ----------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------- 2. Setup Node ----------
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json

      # ---------- 3. Frontend ----------
      - name: Install frontend dependencies
        working-directory: ./client
        run: npm ci || npm install

      - name: Build frontend
        working-directory: ./client
        run: npm run build

      # ---------- 4. Backend ----------
      - name: Install backend dependencies
        working-directory: ./server
        run: npm ci || npm install

      - name: Run backend tests
        working-directory: ./server
        run: npm test || echo "⚠️ No backend tests configured"

      # ---------- 5. Deploy Frontend to Vercel ----------
      - name: Deploy Frontend to Vercel
        if: github.ref == 'refs/heads/main'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          echo "🚀 Deploying Next.js app to Vercel..."
          cd client
          npx vercel pull --yes --environment=production --token $VERCEL_TOKEN
          npx vercel build --token $VERCEL_TOKEN
          npx vercel deploy --prod --yes --token $VERCEL_TOKEN

      # ---------- 6. Deploy Backend to Render ----------
      - name: Deploy Backend to Render
        if: github.ref == 'refs/heads/main'
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          echo "🚀 Triggering Render deployment..."
          curl -X POST "$RENDER_DEPLOY_HOOK"