name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install and lint frontend
      - name: Install frontend dependencies
        working-directory: ./client
        run: npm install

      - name: Lint frontend
        working-directory: ./client
        run: npm run lint || echo "No lint script"

      # Install and test backend
      - name: Install backend dependencies
        working-directory: ./server
        run: npm install

      - name: Run backend tests
        working-directory: ./server
        run: npm test || echo "No tests yet"

      # Optional: Build frontend to verify Next.js build
      - name: Build frontend
        working-directory: ./client
        run: npm run build